name: Deploy to Lolipop FTP

on:
  push:
    branches:
      - main # mainブランチにpushされた時のみ実行。ご自身の環境に合わせて変更してください。

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      
      - name: 📂 Sync files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2222
          source: "./*"
          target: "tech-ramukana.jp/"
          rm: true # 既存のファイルを上書き・クリーンアップする場合
